version: '3'
services:

  server:
    build: ./api
    ports:
      - "3000:3000"
    links:
      - "dbpostgres"
  client:
    build: ./web
    ports:
      - "4032:8080"
    links:
      - server
  dbpostgres:
    image: "postgres"
    volumes:
      - ./db/postgresql:/var/lib/postgresql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "itsallgood"
      POSTGRES_DB: "travel"
    