--
-- PostgreSQL database dump
--

-- Dumped from database version 12.2 (Debian 12.2-2.pgdg100+1)
-- Dumped by pg_dump version 12.2 (Debian 12.2-2.pgdg100+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: "travelNotices"; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."travelNotices" (id, name, travellers, "arrivalDate", "returnDate", "requireAssistance", destination, phone, email, purpose, code, department, "contactedFirstNation", "contactedMunicipality", "contactedOtherGroup", "otherGroupInfo") VALUES (2, 'Ursula Geisler', 1, '2020-05-08', '2020-05-10', false, 'Watson Lake', '8673323144', 'ecc.operationssection@gov.yk.ca', 'Dropping off PPE and other necessary items for the CEMA enforcement officers at the Watson lake station and Junction 37', '', 'Community Services', false, false, false, '');
INSERT INTO public."travelNotices" (id, name, travellers, "arrivalDate", "returnDate", "requireAssistance", destination, phone, email, purpose, code, department, "contactedFirstNation", "contactedMunicipality", "contactedOtherGroup", "otherGroupInfo") VALUES (3, 'Matt Clarke', 1, '2020-05-14', '2020-05-14', false, 'Whitehorse', '667-8640', 'Matt.clarke@gov.yk.ca', 'Computer repair/software upgrade', '', 'Environment', false, false, false, '');
INSERT INTO public."travelNotices" (id, name, travellers, "arrivalDate", "returnDate", "requireAssistance", destination, phone, email, purpose, code, department, "contactedFirstNation", "contactedMunicipality", "contactedOtherGroup", "otherGroupInfo") VALUES (4, 'Carrie Mierau', 3, '2020-05-15', '2020-05-16', false, 'Whitehorse', '8679936850', 'carrie.mierau@gov.yk.ca', 'Travel from Dawson To Whitehorse for 3 employees to pick up Fleet vehicles for seasonal operations at Yukon Parks and Campgrounds, I is flying down and driving back and other 2 are driving down and back.', '', 'Environment', false, false, false, '');
INSERT INTO public."travelNotices" (id, name, travellers, "arrivalDate", "returnDate", "requireAssistance", destination, phone, email, purpose, code, department, "contactedFirstNation", "contactedMunicipality", "contactedOtherGroup", "otherGroupInfo") VALUES (1, 'Brett Isbister', 1, '2020-05-19', '2020-05-21', true, 'Dawson City', '8673349280', 'brett.isbister@gov.yk.ca', 'Inspection at Brewery Creek', NULL, 'Energy, Mines and Resources', false, false, false, '');
INSERT INTO public."travelNotices" (id, name, travellers, "arrivalDate", "returnDate", "requireAssistance", destination, phone, email, purpose, code, department, "contactedFirstNation", "contactedMunicipality", "contactedOtherGroup", "otherGroupInfo") VALUES (2, 'Steven Kromhout', 1, '2020-05-15', '2020-05-15', false, 'Burwash Landing', '867-332-0179', 'steven.kromhout@gov.yk.ca', 'Travelling through Burwash Landing to KM 1728 Alaska Highway (Former Wellgreen Mill and Tailings Site) for an on-site meeting with Kluane First Nation.', NULL, 'Environment', true, false, false, '');
INSERT INTO public."travelNotices" (id, name, travellers, "arrivalDate", "returnDate", "requireAssistance", destination, phone, email, purpose, code, department, "contactedFirstNation", "contactedMunicipality", "contactedOtherGroup", "otherGroupInfo") VALUES (3, 'Shawn Kinsella', 2, '2020-05-15', '2020-05-15', false, 'Watson Lake', '867-667-3230', 'shawn.kinsella@gov.yk.ca', 'Vehicle and freight delivery to Watson Lake Fire Centre, employees will drop off vehicle and freight and then immediately depart', NULL, 'Community Services', false, false, false, '');
INSERT INTO public."travelNotices" (id, name, travellers, "arrivalDate", "returnDate", "requireAssistance", destination, phone, email, purpose, code, department, "contactedFirstNation", "contactedMunicipality", "contactedOtherGroup", "otherGroupInfo") VALUES (4, 'Tim Fordyce', 1, '2020-05-20', '2020-05-22', false, 'Carmacks', '867-456-6718', 'tim.fordyce@gov.yk.ca', 'Electrical Inspections', NULL, 'Community Services', true, false, true, 'Electrical Contractors with outstanding inspections');
INSERT INTO public."travelNotices" (id, name, travellers, "arrivalDate", "returnDate", "requireAssistance", destination, phone, email, purpose, code, department, "contactedFirstNation", "contactedMunicipality", "contactedOtherGroup", "otherGroupInfo") VALUES (5, 'Cheryl Turner', 1, '2020-05-21', '2020-05-21', false, 'Carmacks', '867-335-0556', 'cheryl.turner@gov.yk.ca', 'Install Telehealth Equipment to the Health Centre', NULL, 'Health and Social Services', false, false, true, 'Jennifer Dowling, Nurse-In-Charge, Carmacks Health Centre');
INSERT INTO public."travelNotices" (id, name, travellers, "arrivalDate", "returnDate", "requireAssistance", destination, phone, email, purpose, code, department, "contactedFirstNation", "contactedMunicipality", "contactedOtherGroup", "otherGroupInfo") VALUES (6, 'Cheryl Turner', 1, '2020-05-22', '2020-05-22', false, 'Carcross', '867-335-0556', 'cheryl.turner@gov.yk.ca', 'Install Telehealth Equipment to the Health Centre', NULL, 'Health and Social Services', false, false, true, 'Brook Davis, Nurse-In-Charge, Carcross Health Centre');
INSERT INTO public."travelNotices" (id, name, travellers, "arrivalDate", "returnDate", "requireAssistance", destination, phone, email, purpose, code, department, "contactedFirstNation", "contactedMunicipality", "contactedOtherGroup", "otherGroupInfo") VALUES (7, 'cory chouinard', 2, '2020-05-22', '2020-05-29', false, 'Dawson City', '8673361387', 'cory.chouinard@gov.yk.ca', 'Tree planting contract', NULL, 'Energy, Mines and Resources', true, false, true, 'CMI');
INSERT INTO public."travelNotices" (id, name, travellers, "arrivalDate", "returnDate", "requireAssistance", destination, phone, email, purpose, code, department, "contactedFirstNation", "contactedMunicipality", "contactedOtherGroup", "otherGroupInfo") VALUES (8, 'Mark Ritchie', 2, '2020-05-25', '2020-05-29', false, 'Old Crow', '867-634-2948', 'mark.ritchie@gov.yk.ca', 'Community Aerodrome Radio Station Employee Re-certifications', NULL, 'Highways and Public Works', true, false, true, 'Airport Staff');
INSERT INTO public."travelNotices" (id, name, travellers, "arrivalDate", "returnDate", "requireAssistance", destination, phone, email, purpose, code, department, "contactedFirstNation", "contactedMunicipality", "contactedOtherGroup", "otherGroupInfo") VALUES (9, 'Shawn Kinsella', 1, '2020-05-19', '2020-05-19', false, 'Mayo', '867-667-3230', 'shawn.kinsella@gov.yk.ca', 'Vehicle swap and freight delivery to the Mayo Fire Centre, immediate departure after offload', NULL, 'Community Services', false, false, false, '');
INSERT INTO public."travelNotices" (id, name, travellers, "arrivalDate", "returnDate", "requireAssistance", destination, phone, email, purpose, code, department, "contactedFirstNation", "contactedMunicipality", "contactedOtherGroup", "otherGroupInfo") VALUES (10, 'Shawn Kinsella', 1, '2020-05-19', '2020-05-19', false, 'Carmacks', '867-667-3230', 'shawn.kinsella@gov.yk.ca', 'Freight delivery to Carmacks Fire Centre, offload and immediate departure', NULL, 'Community Services', false, false, false, '');
INSERT INTO public."travelNotices" (id, name, travellers, "arrivalDate", "returnDate", "requireAssistance", destination, phone, email, purpose, code, department, "contactedFirstNation", "contactedMunicipality", "contactedOtherGroup", "otherGroupInfo") VALUES (11, 'Robert Wondga', 1, '2020-05-25', '2020-05-29', false, 'Dawson City', '667-8919', 'robert.wondga@gov.yk.ca', 'community visits to Dawson, Mayo, Carmacks, Ross River', NULL, 'Community Services', false, false, true, 'The CS departments');
INSERT INTO public."travelNotices" (id, name, travellers, "arrivalDate", "returnDate", "requireAssistance", destination, phone, email, purpose, code, department, "contactedFirstNation", "contactedMunicipality", "contactedOtherGroup", "otherGroupInfo") VALUES (12, 'Russell Trimble ', 1, '2020-05-20', '2020-05-20', false, 'Mayo', '867-332-5228', 'russell.trimble@gov.yk.ca', 'Whitehorse to Mayo for inspection of airport for future development.', NULL, 'Highways and Public Works', false, false, false, '');
INSERT INTO public."travelNotices" (id, name, travellers, "arrivalDate", "returnDate", "requireAssistance", destination, phone, email, purpose, code, department, "contactedFirstNation", "contactedMunicipality", "contactedOtherGroup", "otherGroupInfo") VALUES (13, 'Stuart Reimer', 1, '2020-05-20', '2020-05-20', false, 'Mayo', '867-993-7719', 'Stuart.Reimer@gov.yk.ca', 'Airport Maintenance', NULL, 'Highways and Public Works', false, false, false, '');
INSERT INTO public."travelNotices" (id, name, travellers, "arrivalDate", "returnDate", "requireAssistance", destination, phone, email, purpose, code, department, "contactedFirstNation", "contactedMunicipality", "contactedOtherGroup", "otherGroupInfo") VALUES (14, 'Jeff Stephenson', 1, '2020-05-20', '2020-05-20', false, 'Mayo', '867-993-3992', 'Jeff.Stephenson@gov.yk.ca', 'Airport Maintenance, one day a week.', NULL, 'Highways and Public Works', false, false, false, '');
INSERT INTO public."travelNotices" (id, name, travellers, "arrivalDate", "returnDate", "requireAssistance", destination, phone, email, purpose, code, department, "contactedFirstNation", "contactedMunicipality", "contactedOtherGroup", "otherGroupInfo") VALUES (15, 'Peter Bazett', 1, '2020-05-22', '2020-05-22', false, 'Carmacks', '867-334-5601', 'peter.bazett@gov.yk.ca', 'Monthly fire alarm and generator testing (school and nursing stn.)', NULL, 'Highways and Public Works', false, false, true, 'Nursing stn., School');
INSERT INTO public."travelNotices" (id, name, travellers, "arrivalDate", "returnDate", "requireAssistance", destination, phone, email, purpose, code, department, "contactedFirstNation", "contactedMunicipality", "contactedOtherGroup", "otherGroupInfo") VALUES (16, 'Neal Allison', 2, '2020-05-20', '2020-05-21', false, 'Haines Junction', '867-334-5896', 'neal.allison@gov.yk.ca', 'Setting up spruce bark beetle traps.', NULL, 'Energy, Mines and Resources', false, false, false, '');
INSERT INTO public."travelNotices" (id, name, travellers, "arrivalDate", "returnDate", "requireAssistance", destination, phone, email, purpose, code, department, "contactedFirstNation", "contactedMunicipality", "contactedOtherGroup", "otherGroupInfo") VALUES (17, 'Adam Wicke', 1, '2020-05-19', '2020-05-22', false, 'Mayo', '867-332-4991', 'adam.wicke@gmail.com', 'Coverage of Regional Office (Social Work)', NULL, 'Health and Social Services', true, false, false, '');
INSERT INTO public."travelNotices" (id, name, travellers, "arrivalDate", "returnDate", "requireAssistance", destination, phone, email, purpose, code, department, "contactedFirstNation", "contactedMunicipality", "contactedOtherGroup", "otherGroupInfo") VALUES (18, 'Dorothy Magun', 1, '2020-05-26', '2020-05-29', false, 'Whitehorse', '1-867-536-3220', 'dmmagun@gov.yk.ca', 'Training at the Whitehorse Yukon Community Corrections Office', NULL, 'Justice', false, false, false, '');
INSERT INTO public."travelNotices" (id, name, travellers, "arrivalDate", "returnDate", "requireAssistance", destination, phone, email, purpose, code, department, "contactedFirstNation", "contactedMunicipality", "contactedOtherGroup", "otherGroupInfo") VALUES (19, 'Krisztian Kalanz', 1, '2020-05-25', '2020-05-26', false, 'Whitehorse', '867-334-2187', 'kristian.kalanz@gov.yk.ca', 'Fleet servicing, change studded tires to all seasons', NULL, 'Health and Social Services', false, false, false, '');
INSERT INTO public."travelNotices" (id, name, travellers, "arrivalDate", "returnDate", "requireAssistance", destination, phone, email, purpose, code, department, "contactedFirstNation", "contactedMunicipality", "contactedOtherGroup", "otherGroupInfo") VALUES (20, 'Krisztian Kalasz', 1, '2020-05-26', '2020-05-29', false, 'Carmacks', '1867-334-2187', 'krisztian.kalasz@gov.yk.ca', 'will travel to Carmacks and Pelly Crossing providing itinerant work, mental health support', NULL, 'Health and Social Services', false, false, false, '');
INSERT INTO public."travelNotices" (id, name, travellers, "arrivalDate", "returnDate", "requireAssistance", destination, phone, email, purpose, code, department, "contactedFirstNation", "contactedMunicipality", "contactedOtherGroup", "otherGroupInfo") VALUES (21, 'Caroline Alain', 2, '2020-05-21', '2020-05-21', false, 'Burwash Landing', '867-333-9718', 'Caroline.Alain@gov.yk.ca', 'home care regional therapy visit', NULL, 'Health and Social Services', true, false, false, '');
INSERT INTO public."travelNotices" (id, name, travellers, "arrivalDate", "returnDate", "requireAssistance", destination, phone, email, purpose, code, department, "contactedFirstNation", "contactedMunicipality", "contactedOtherGroup", "otherGroupInfo") VALUES (22, 'Shawn Kinsella', 1, '2020-05-21', '2020-05-21', false, 'Haines Junction', '867-667-3230', 'shawn.kinsella@gov.yk.ca', 'Freight delivery to HJ Fire Centre, Offload and immediate departure', NULL, 'Community Services', false, false, false, '');
INSERT INTO public."travelNotices" (id, name, travellers, "arrivalDate", "returnDate", "requireAssistance", destination, phone, email, purpose, code, department, "contactedFirstNation", "contactedMunicipality", "contactedOtherGroup", "otherGroupInfo") VALUES (23, 'Louis Gerberding', 1, '2020-06-08', '2020-06-12', true, 'Old Crow', '867-993-5499', 'louis.gerberding@gov.yk.ca', 'Training of the new custodial staff at the school', NULL, 'Highways and Public Works', false, false, false, '');
INSERT INTO public."travelNotices" (id, name, travellers, "arrivalDate", "returnDate", "requireAssistance", destination, phone, email, purpose, code, department, "contactedFirstNation", "contactedMunicipality", "contactedOtherGroup", "otherGroupInfo") VALUES (24, 'Caroline Alain', 2, '2020-06-01', '2020-06-04', false, 'Watson Lake', '867-333-9718', 'caroline.alain@gov.yk.ca', 'Regional OT/PT home care visit', NULL, 'Health and Social Services', false, false, true, 'home care coordinator and clients');
INSERT INTO public."travelNotices" (id, name, travellers, "arrivalDate", "returnDate", "requireAssistance", destination, phone, email, purpose, code, department, "contactedFirstNation", "contactedMunicipality", "contactedOtherGroup", "otherGroupInfo") VALUES (25, 'Rowan Brown', 2, '2020-05-25', '2020-05-25', true, 'Haines Junction', '8673344998', 'rowan.brown@gov.yk.ca', 'Field work - will be working in remote forestry areas - no interactions with community members expected.', NULL, 'Energy, Mines and Resources', false, false, false, '');
INSERT INTO public."travelNotices" (id, name, travellers, "arrivalDate", "returnDate", "requireAssistance", destination, phone, email, purpose, code, department, "contactedFirstNation", "contactedMunicipality", "contactedOtherGroup", "otherGroupInfo") VALUES (26, 'vernon marshall', 2, '2020-05-25', '2020-05-29', false, 'Dawson City', '8673322078', 'vern.marshall@gov.yk.ca', 'Radio Service', NULL, 'Community Services', false, true, false, '');
INSERT INTO public."travelNotices" (id, name, travellers, "arrivalDate", "returnDate", "requireAssistance", destination, phone, email, purpose, code, department, "contactedFirstNation", "contactedMunicipality", "contactedOtherGroup", "otherGroupInfo") VALUES (27, 'Chris Faloon', 1, '2020-05-26', '2020-05-26', true, 'Carcross', '867-456-6124', 'chris.faloon@gov.yk.ca', 'To complete a site visit for the completion of a Phase 1 Environmental Assessment. This work only will take and hour or so and involve only walking around the site.', NULL, 'Environment', false, false, false, '');
INSERT INTO public."travelNotices" (id, name, travellers, "arrivalDate", "returnDate", "requireAssistance", destination, phone, email, purpose, code, department, "contactedFirstNation", "contactedMunicipality", "contactedOtherGroup", "otherGroupInfo") VALUES (28, 'Kylie Campbell', 1, '2020-06-02', '2020-06-02', false, 'Teslin', '8673322705', 'kylie.campbell@gov.yk.ca', 'A Contractor will connect and install Variable Message Boards outside town limits (Alaska Highway Km 1251 and Km 1239).', NULL, 'Highways and Public Works', false, false, false, '');
INSERT INTO public."travelNotices" (id, name, travellers, "arrivalDate", "returnDate", "requireAssistance", destination, phone, email, purpose, code, department, "contactedFirstNation", "contactedMunicipality", "contactedOtherGroup", "otherGroupInfo") VALUES (29, 'Hyder Bos-Jabbar', 2, '2020-05-26', '2020-05-28', true, 'Haines Junction', '8673333834', 'hyder.bos-jabbar@gov.yk.ca', 'To train wildfire Initial Attack crews in order to be fully operational and capable for wildfire suppression operations.

Have spoken with Kluane Fire Center about travel plans. ', NULL, 'Community Services', false, false, false, '');
INSERT INTO public."travelNotices" (id, name, travellers, "arrivalDate", "returnDate", "requireAssistance", destination, phone, email, purpose, code, department, "contactedFirstNation", "contactedMunicipality", "contactedOtherGroup", "otherGroupInfo") VALUES (30, 'Nadine Nicholson', 1, '2020-05-26', '2020-05-26', false, 'Carcross', '8674565534', 'nadine.nicholson@gov.yk.ca', 'Inspections- Carcross Tagish', NULL, 'Health and Social Services', false, false, false, '');
INSERT INTO public."travelNotices" (id, name, travellers, "arrivalDate", "returnDate", "requireAssistance", destination, phone, email, purpose, code, department, "contactedFirstNation", "contactedMunicipality", "contactedOtherGroup", "otherGroupInfo") VALUES (31, 'Chris Locke', 1, '2020-05-26', '2020-05-28', false, 'Dawson City', '867-667-3186', 'chris.locke@gov.yk.ca', 'Deployment Wildland Fire MICP Trailer ', NULL, 'Community Services', false, false, true, 'manager Wildland Fire Brian Douglas');


--
-- Name: "travelNotices"_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."travelNotices_id_seq"', 31, true);


--
-- PostgreSQL database dump complete
--
