export default {
  communities: "/getCommunities",
  communityGroups: "/getCommunityGroups",
  departments: "/getDepartments",
  createNotice: "/createNotice",
  updateNotice: "/updateNotice",
  deleteNotice: "/deleteNotice",
  flagNotice: "/flagNotice",
  getNotices: "/getNotices",
  getNotice: "/getNotice/",
  getNoticesByCommunity: "/getNotices/byCommunity/",
  getNoticesByDepartment: "/getNotices/byDepartment/",
  getNoticesRollup: "/getNotices",
  getEmails: "/getEmails",
  getEmailsByCommunity: "/getEmailsByCommunity/",
  getEmailsByDepartment: "/getEmailsByDepartment/",
  createEmail: "/createEmail",
  updateEmail: "/updateEmail/",
  deleteEmail: "/deleteEmail/"
}
